CREATE TABLE IF NOT EXISTS CAMPAIGNS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    start_date DATE,
    bid DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    category VARCHAR(100),
    price DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS CAMPAIGN_PRODUCT (
    campaign_id INT,
    product_id INT,
    PRIMARY KEY (campaign_id, product_id),
    FOREIGN KEY (campaign_id) REFERENCES CAMPAIGNS(id),
    FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);
